services:
  - type: web
    name: predictions
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn predictions.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: predictions.settings 